# Generated by Django 3.2.4 on 2021-06-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('pos', models.CharField(choices=[('CF', 'Center-Forward'), ('SS', 'Second-Striker'), ('LWF', 'Left-Winger'), ('RWF', 'Right-Winger')], max_length=3)),
                ('nationality', models.CharField(max_length=10)),
            ],
        ),
    ]
